required = [
  "k8s.io/client-go/discovery",
]

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "github.com/logrusorgru/aurora"
  revision = "a7b3b318ed4e1ae5b80602b08627267303c68572"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "02948caff2f67a31b8f548c412d5b9d0a46bf11d"

[prune]
  go-tests = true
  unused-packages = true
