on: push
name: Push
jobs:
  checks:
    name: checks
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Run all checks
      uses: cedrickring/golang-action@1.3.0
      env:
        GO111MODULE: "on"
