on: release
name: Release
jobs:
  build_and_release:
    name: build and release binaries
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Build all binaries
      uses: cedrickring/golang-action@1.3.0
      env:
        GO111MODULE: "on"
      with:
        args: make build-all

    - name: Upload windows release
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: out/kbuild_windows_amd64.exe application/octet-stream

    - name: Upload linux release
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: out/kbuild_linux_amd64 application/octet-stream

    - name: Upload darwin release
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: out/kbuild_darwin_amd64 application/octet-stream
